"""empty message

Revision ID: 09759ef28955
Revises: 0763d677d453
Create Date: 2026-02-09 12:19:06.008716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09759ef28955'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
